version: '2.6.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpwd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306